### ISSUE TITLE
ZeroDivisionError at cli.py (new_line_callback) when processing small silence intervals

### ISSUE THREAD

**Issue by Murilo-Perrone** [autoscrib/autoscrib.github.io#1]
I'm getting crashes when trying to autoscrub some long videos from Teams meeting recordings:

```> autoscrub autoprocess  --speed 64 --target-threshold -40 --silence-duration 0.5  --delay 0  "file.mp4" "file_scrub.mp4"
[autoscrub:info] Processing file.mp4
[ffprobe] Getting audio sample rate...
[ffmpeg:ebur128] Checking loudness of file...
[autoscrub:info] Measured loudness = -19.6 dBLUFS; Silence threshold = -41.6 dB; Gain to apply = 1.6 dB
[ffmpeg:silencedetect] Searching for silence...
[ffmpeg:silencedetect] Completed in 00:01:37                   
[autoscrub:info] Found 1215 silences of average duration 2.3 seconds.
[autoscrub:info] Generating ffmpeg filter_complex script...
[autoscrub:info] autoscrubbing video
Traceback (most recent call last):
  File "/usr/local/bin/autoscrub", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/autoscrub/scripts/cli.py", line 276, in autoprocess
    result = autoscrub.ffmpegComplexFilter(input, filter_graph_path, output, run_command=True, overwrite=True, stderr_callback=callback)
  File "/usr/local/lib/python3.9/site-packages/autoscrub/__init__.py", line 1107, in ffmpegComplexFilter
    stdout, stderr = _agnostic_communicate(p, new_line_callback=stderr_callback)
  File "/usr/local/lib/python3.9/site-packages/autoscrub/__init__.py", line 185, in _agnostic_communicate
    new_line_callback(local_buffer)
  File "/usr/local/lib/python3.9/site-packages/autoscrub/scripts/cli.py", line 100, in new_line_callback
    time_remaining = (time.time()-self.start_time)/percentage*(100-percentage)
ZeroDivisionError: float division by zero
```

Checking the code, it will crash whenever `seconds` is zero or `seconds >= duration`, since that will result percentage being 0 or 100.
```
    percentage = min(float(seconds)/self.duration, 1)*100
    time_remaining = (time.time()-self.start_time)/percentage*(100-percentage)
```

**Comment by madeInLagny** [comment]
This is autoScrib repo. You refer to another one
